apiVersion: v1
kind: Service
metadata:
  name: graphite-web-service
  namespace: devops-test
spec:
  type: LoadBalancer
  selector:
    app: statsd
  ports:
    - name: graphite-web
      protocol: TCP
      port: 80
      targetPort: 80
