apiVersion: v1
kind: Service
metadata:
  name: statsd-udp-service
  namespace: devops-test
spec:
  type: ClusterIP
  selector:
    app: statsd
  ports:
    - name: statsd-udp
      protocol: UDP
      port: 8125
      targetPort: 8125
